name: Build and test container images

on:
  pull_request:
  push:
    branches: [main, dev]
  workflow_dispatch:

permissions: {}

jobs:
  build-basic:
    permissions:
      contents: read
      actions: read
      packages: write
      id-token: write
    uses: ./.github/workflows/reusable-build-and-publish-one-image.yml
    with:
      image-name: test-basic
      containerfile: ./examples/Containerfile.basic
      context: .
      platform: linux/amd64
      free-disk-space: false
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}

  build-derived:
    permissions:
      contents: read
      actions: read
      packages: write
      id-token: write
    uses: ./.github/workflows/reusable-build-and-publish-one-image.yml
    with:
      image-name: test-derived
      containerfile: ./examples/Containerfile.derived
      context: .
      platform: linux/amd64
      build-args: BASE_IMAGE=ghcr.io/ublue-os/arch-toolbox:latest
      cosign-public-key: https://raw.githubusercontent.com/ublue-os/main/main/cosign.pub
      free-disk-space: false
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}

  test-slsa:
    needs: [build-basic]
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      actions: read
      packages: write
      id-token: write
    uses: ./.github/workflows/reusable-build-and-publish-one-image.yml
    with:
      image-name: test-slsa
      containerfile: ./examples/Containerfile.slsa
      context: .
      platform: linux/amd64
      slsa-verify-source: github.com/MArpogaus/image-builder-action
      free-disk-space: false
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}

  build-overwrite-tag:
    permissions:
      contents: read
      actions: read
      packages: write
      id-token: write
    uses: ./.github/workflows/reusable-build-and-publish-one-image.yml
    with:
      image-name: test-overwrite
      containerfile: ./examples/Containerfile.basic
      context: .
      platform: linux/amd64
      overwrite-ref-tag: test
      free-disk-space: false
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
